Update docs for Wii compilation of RetroArch Wii
libretro/docs pull request #833
Opened 2023-05-03 18:55 UTC by saulfabregwiivc

Fix some bad spelling on the Wii docs for compiling, add some info, add another way for compiling cores ;)

2023-05-03 20:30 UTC, hizzlekizzle commented
Thanks for taking the time to improve the doc!

I added a few notes.

2023-05-04 18:51 UTC, saulfabregwiivc commented
> I added a few notes.

Sorry i'm not a GitHub expert but where I can see your notes?

2023-05-04 21:21 UTC, hizzlekizzle requested changes

2023-05-04 21:21 UTC, hizzlekizzle commented on docs/development/retroarch/compilation/wii.md
> +To update your local copy from the repository of RetroArch, run git pull
I agree that the original wording was ambiguous, but I think this should probably read: "To update your local copy of the RetroArch repository, run git pull".

2023-05-04 21:21 UTC, hizzlekizzle commented on docs/development/retroarch/compilation/wii.md
> +For compile Salamander (for Wii) run:
I believe "To" is correct here.

2023-05-04 21:21 UTC, hizzlekizzle commented on docs/development/retroarch/compilation/wii.md
> +Second, to compile RetroArch for Wii (the core and the frontend), rename the compiled core as 'libretro_wii.a' (see below how to compile a core on "Building Cores" section), put it in the RetroArch d
Good catch!

I think the preposition "on" should be changed to "in the".

2023-05-04 21:21 UTC, hizzlekizzle commented on docs/development/retroarch/compilation/wii.md
> +Another way for compile the cores, is cloning the core's repository (for example, FCEUmm) from [GitHub](https://github.com/orgs/libretro/repositories).
"Another way _to compile cores is by_ cloning the core's repository..."

2023-05-04 21:21 UTC, hizzlekizzle commented on docs/development/retroarch/compilation/wii.md
> +In this case, for clone FCEUmm-Libretro repo:
for -> to

2023-05-04 21:21 UTC, hizzlekizzle commented on docs/development/retroarch/compilation/wii.md
> +For compile the core for Wii (in this case, FCEUmm) run:
For -> To

2023-05-04 21:22 UTC, hizzlekizzle commented
oh whoops, I think they were not visible to you. sorry about that. they should show up now.

2023-05-06 00:27 UTC, saulfabregwiivc commented
Fixed the spelling issues, considering your suggestions.

2023-05-06 11:06 UTC, merged