New GUI pages, pages split out, some cleanup
libretro/docs pull request #938
Opened 2024-05-07 18:12 UTC by Jaffacakelover

Created pages for the other GUIs. Split "Starting a game" and "disk swapping" out into their own pages. Added new images. Added a few cross-references. General cleanup.

2024-05-10 18:49 UTC, fpscan requested changes
It is best to have non-nintendo stuff.

2024-05-10 18:49 UTC, fpscan commented on docs/image/retroarch/xmb/thumbnails1.png
Is it possible to have different thumbnails?

2024-05-13 11:42 UTC, Jaffacakelover commented
Understandable, yes. Amending the pics now: If anyone can name this filter (or grab me a new AltStore screenshot) that'd help out.
![screenshot5](https://github.com/libretro/docs/assets/3490850/0adca2ec-22ac-46ff-aee4-ddd9bda7eeeb)

2024-05-13 15:45 UTC, fpscan commented
> Understandable, yes. Amending the pics now: If anyone can name this filter (or grab me a new AltStore screenshot) that'd help out. ![screenshot5](https://private-user-images.githubusercontent.com/3490850/330040831-0adca2ec-22ac-46ff-aee4-ddd9bda7eeeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTUzODEsIm5iZiI6MTcxNTYxNTA4MSwicGF0aCI6Ii8zNDkwODUwLzMzMDA0MDgzMS0wYWRjYTJlYy0yMmFjLTQ2ZmYtYWVlNC1kZGQ5YmRhN2VlZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTU0NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFiYjVhY2UxMTcwNDEzOWM2OWNiMjIzODAyYWMzNjk3MjBlZmFhZmY5MDBlODY4MGRmMDQxMjMzYjc2NzBhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wGdEjzrAGAo79ZBfq4mexjyrLCQU6-iPc95OUx4WX2M)
@hizzlekizzle any wild guesses?

2024-05-14 18:20 UTC, Jaffacakelover commented
Found it: `Slang > Bezel > Mega Bezel`. I'll use `Presets > MBZ__2__ADV-GLASS` for my shot.

2024-05-20 19:04 UTC, Jaffacakelover commented
That should do it, unless you want me to delve into all the per-Core images and Shader examples.

2024-05-27 08:14 UTC, merged